# Generated by Django 3.2.5 on 2021-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_b64',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
