# Generated by Django 3.2.5 on 2021-07-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210727_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
