# Generated by Django 3.2.5 on 2021-07-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_home_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image_b64',
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.FileField(db_column='image', upload_to=''),
        ),
    ]
