# Generated by Django 3.2.5 on 2021-07-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210729_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.TextField(db_column='image'),
        ),
    ]
