# Generated by Django 3.2.5 on 2021-07-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.FileField(blank=True, db_column='image', upload_to=''),
        ),
    ]
