# Generated by Django 3.2.5 on 2021-07-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.BinaryField(blank=True, db_column='image'),
        ),
    ]
