# Generated by Django 3.2.5 on 2021-08-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210802_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.TextField(),
        ),
    ]
