# Generated by Django 3.2.5 on 2021-08-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allprogrammes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=5000000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'Allprogrammes',
            },
        ),
    ]
