# Generated by Django 3.2.5 on 2021-08-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210825_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequirement',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='allprogrammes',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='campus',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hndfulltime',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hndparttime',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ndfulltime',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ndparttime',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nsukka',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postutme',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
